name: fgrestaurant
description: Fresh genie restaurant app.
version: 1.0.0+1

environment:
   sdk: '>=2.1.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   cupertino_icons: ^0.1.2
   cloud_firestore: ^0.13.4+1
   google_sign_in: ^4.1.1
   firebase_auth: ^0.14.0
   localstorage: ^3.0.1+4
   pinput: ^0.1.10
   dotted_border: ^1.0.5
   ant_icons: ^1.0.0
   fl_chart: ^0.8.7
   after_layout: ^1.0.7+2
   http: ^0.12.0+2
   provider: ^3.1.0
   firebase_storage: ^3.1.3
   location: ^2.5.3
   intl: ^0.16.1
   image_picker: ^0.6.0+15
   google_fonts: ^0.3.2
   path_provider: ^1.5.1
   flip_card: ^0.4.4
   shared_preferences: ^0.5.6
   get_it: ^1.0.3+2
   latlong: ^0.6.1
   google_maps_flutter: ^0.5.24+1
   paytm: ^1.0.0
   geolocator: ^5.2.0

dev_dependencies:
   flutter_test:
      sdk: flutter

flutter:
   uses-material-design: true
   # To add assets to your application, add an assets section, like this:
   assets:
      - assets/pngs/

   fonts:
      - family: DankMonoRegular
        fonts:
           - asset: assets/fonts/DankMono-Regular.ttf
